version: 3.8

services:
  app:
    build:
      context: .
      dockerfile: DockerFile
    restart: always
    ports:
      - "8080:8080"
    entrypoint: jdbc:postgresql://localhost:5432/library_db
    depends_on:
      - postgres


  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER:postgres
      - POSTGRES_DB:postgres
      - POSTGRES_PASSWORD:root
    volumes:
      - "pg-data:/var/postgresql/data"

volumes:
  pg-data: { }
