create table authors
(
    id          int8 generated by default as identity,
    name        varchar(30),
    parent_name varchar(30),
    surname     varchar(45),
    primary key (id)
);
create table book
(
    id          int8 generated by default as identity,
    isbn        varchar(60),
    book_status varchar(15),
    description varchar(500),
    title       varchar(60),
    primary key (id)
);

create table book_authors
(
    book_id    int8 not null,
    authors_id int8 not null
);

create table book_genres
(
    book_id int8 not null,
    genres  varchar(20)
);

create table journal
(
    id                  int8 generated by default as identity,
    date_of_get_book    date,
    date_of_return_book date,
    book_id             int8,
    primary key (id)
);

create table library_users
(
    id          int8 generated by default as identity,
    name        varchar(30),
    parent_name varchar(30),
    password    varchar(60),
    surname     varchar(40),
    username    varchar(100),
    primary key (id)
);

create table user_roles
(
    user_id int8 not null,
    roles   varchar(20)
);

alter table if exists book_authors
    add constraint unique_authors_id unique (authors_id);

alter table if exists book_authors
    add constraint authors_id_FK_book_authors foreign key (authors_id) references authors;

alter table if exists book_authors
    add constraint book_id_FK_book_authors foreign key (book_id) references book;

alter table if exists book_genres
    add constraint book_id_FK_book_genres foreign key (book_id) references book;

alter table if exists journal_book
    add constraint book_id_FK_journal_book foreign key (book_id) references book;

alter table if exists user_roles
    add constraint user_id_FK_user_roles foreign key (user_id) references library_users;
